app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from carts.views import CartAddView, CartChangeView, CartRemoveView

app_name = 'cart'

urlpatterns = [
    path('cart_add/', CartAddView.as_view(), name='cart_add'),
    path('cart_change/', CartChangeView.as_view(), name='cart_change'),
    path('cart_remove/', CartRemoveView.as_view(), name='cart_remove'),
]

goods/urls.py
from django.urls import path

from goods.views import CatalogView, ProductView

app_name = 'goods'

urlpatterns = [
    path('search/', CatalogView.as_view(), name='search'),
    path('<slug:category_slug>/', CatalogView.as_view(), name='index'),
    path('product/<slug:product_slug>/', ProductView.as_view(), name='product'),
]

goods/models.py
from decimal import Decimal

from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        db_table = 'categories'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self) -> str:
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, default='', verbose_name='Описание')
    image = models.ImageField(
        upload_to='goods_images',
        blank=True,
        null=True,
        verbose_name='Изображение',
    )
    price = models.DecimalField(
        default=Decimal('0.00'),
        max_digits=7,
        decimal_places=2,
        verbose_name='Цена',
    )
    discount = models.DecimalField(
        default=Decimal('0.00'),
        max_digits=4,
        decimal_places=2,
        verbose_name='Скидка в %',
    )
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'products'
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ('id',)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product', kwargs={'product_slug': self.slug})

    def show_id(self):
        return f'{self.id:05}'

    def actual_price(self):
        if self.discount:
            return round(self.price * (1 - self.discount / 100), 2)
        return self.price

goods/views.py
from django.views.generic import DetailView, ListView

from goods.models import Product
from goods.utils import q_search


class CatalogView(ListView):
    model = Product
    template_name = 'goods/catalog.html'
    queryset = Product.objects.filter(quantity__gt=0)
    context_object_name = 'products'
    paginate_by = 3

    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug')
        on_sale = self.request.GET.get('on_sale', None)
        order_by = self.request.GET.get('order_by', None)
        query = self.request.GET.get('q', None)

        if category_slug == 'all':
            products = super().get_queryset()
        elif query:
            products = q_search(query)
        else:
            products = super().get_queryset().filter(category__slug=category_slug)

        if on_sale:
            products = products.filter(discount__gt=0)
        if order_by and order_by != 'default':
            products = products.order_by(order_by)

        return products

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': 'Home - Каталог',
            'slug_url': self.kwargs.get('category_slug'),
            'total_products': context['page_obj'].paginator.count,
        })
        return context


class ProductView(DetailView):
    template_name = 'goods/product.html'
    slug_url_kwarg = 'product_slug'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': self.object.name})
        return context

    def get_object(self) -> Product:
        product = Product.objects.get(slug=self.kwargs.get(self.slug_url_kwarg))
        return product

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}
{% block modal_cart %}
    {% include "includes/cart_button.html" %}
{% endblock modal_cart %}
{% block content %}
    <div class="row">
        <!-- Форма фильтров -->
        {% if products %}
            <div class="dropdown mb-2">
                <button class="btn btn-secondary dropdown-toggle btn-dark"
                        type="button"
                        data-bs-toggle="dropdown"
                        aria-expanded="false">Фильтры</button>
                <h1 class="results-counter">Всего результатов: {{ total_products }}</h1>
                <form action="{% if request.GET.q %}{% url "catalog:search" %}{% else %}{% url 'catalog:index' slug_url %}{% endif %}"
                      method="get"
                      class="dropdown-menu bg-dark"
                      data-bs-theme="dark">
                    <div class="form-check text-white mx-3" if>
                        <input class="form-check-input"
                               type="checkbox"
                               name="on_sale"
                               id="flexCheckDefault"
                               value="on"
                               {% if request.GET.on_sale == 'on' %}checked{% endif %} />
                        {% if request.GET.q %}<input type="hidden" name="q" value={{ request.GET.q }} />{% endif %}
                        <label class="form-check-label" for="flexCheckDefault">Товары по акции</label>
                    </div>
                    <p class="text-white mx-3 mt-3">Сортировать:</p>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input"
                               type="radio"
                               name="order_by"
                               value="default"
                               id="flexRadioDefault1"
                               {% if not request.GET.order_by %}checked{% endif %} />
                        <label class="form-check-label" for="flexRadioDefault1">По умолчанию</label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input"
                               type="radio"
                               name="order_by"
                               id="flexRadioDefault2"
                               value="price"
                               {% if request.GET.order_by == 'price' %}checked{% endif %} />
                        <label class="form-check-label" for="flexRadioDefault2">Сначала дешевые</label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input"
                               type="radio"
                               name="order_by"
                               id="flexRadioDefault3"
                               value="-price"
                               {% if request.GET.order_by == '-price' %}checked{% endif %} />
                        <label class="form-check-label" for="flexRadioDefault3">Сначала дорогие</label>
                    </div>
                    <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
                </form>
            </div>
            <!-- Карта товара -->
            {% for product in products %}
                <div class="col-lg-4 col-md-6 p-4">
                    <div class="card border-primary rounded custom-shadow">
                        {% if product.image %}
                            <img src="{{ product.image.url }}" class="card-img-top" alt="..." />
                        {% else %}
                            <img src="{% static 'deps/images/Not found image.png' %}"
                                 class="card-img-top"
                                 alt="..." />
                        {% endif %}
                        <div class="card-body">
                            <a href="{{ product.get_absolute_url }}">
                                <p class="card-title">
                                    {% if product.headline %}
                                        {{ product.headline|safe }}
                                    {% else %}
                                        {{ product.name }}
                                    {% endif %}
                                </p>
                            </a>
                            <p class="card-text">
                                {% if product.bodyline %}
                                    {{ product.bodyline|safe|truncatechars:100 }}
                                {% else %}
                                    {{ product.description|truncatechars:50 }}
                                {% endif %}
                            </p>
                            <p class="product_id">id: {{ product.show_id }}</p>
                            <div class="d-flex justify-content-between">
                                {% if product.discount %}
                                    <p>
                                        <s>{{ product.actual_price }} $</s>
                                    </p>
                                    <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                                {% endif %}
                                <p>
                                    <strong>{{ product.price }}</strong> $
                                </p>
                                <a href="{% url "cart:cart_add" %}"
                                   class="btn add-to-cart"
                                   data-product-id="{{ product.id }}">
                                    {% csrf_token %}
                                    <img class="mx-1"
                                         src="{% static 'deps/icons/cart-plus.svg' %}"
                                         alt="Catalog Icon"
                                         width="32"
                                         height="32" />
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <!-- Пагинация -->
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center mb-4">
                <div class="custom-shadow d-flex">
                    <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_previous %}?{% change_params page=page_obj.previous_page_number %}{% endif %}">Пред.</a>
                    </li>
                    {% for page in page_obj.paginator.page_range %}
                        {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                            <li class="page-item {% if page_obj.number == page %}active{% endif %}">
                                <a class="page-link" href="?{% change_params page=page %}">{{ page }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                        <a class="page-link"
                           href="{% if page_obj.has_next %}?{% change_params page=page_obj.next_page_number %}{% endif %}">След.</a>
                    </li>
                </div>
            </ul>
        </nav>
    {% else %}
        <h1>Ничего не найдено 😢</h1>
    {% endif %}
{% endblock content %}

goods/templates/goods/product.html
{% extends 'base.html' %}
{% load static %}
{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock modal_cart %}
{% block content %}
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow">
            <div class="row">
                <!-- Миниатюры -->
                <div class="col-md-4">
                    <img src="{{ product.image.url }}"
                         class="img-thumbnail"
                         data-bs-toggle="modal"
                         data-bs-target="#imageModal1" />
                </div>
                <div class="col-md-4">
                    <p class="product_id mt-3">id: {{ product.show_id }}</p>
                </div>
                <!-- Увеличить изображение в модальном окне -->
                <div class="modal fade"
                     id="imageModal1"
                     tabindex="-1"
                     aria-labelledby="imageModal1Label"
                     aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                                <button type="button"
                                        class="btn-close"
                                        data-bs-dismiss="modal"
                                        aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{ product.image.url }}" class="img-fluid" alt="Изображение 1" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Описание товара -->
            <div class="card-body">
                <p class="card-text">
                    Цена: <strong>150.00 $</strong>
                </p>
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <a href="{% url "cart:cart_add" %}"
                   class="btn btn-dark add-to-cart"
                   data-product-id="{{ product.id }}">{% csrf_token %}Добавить в корзину</a>
            </div>
        </div>
    </div>
{% endblock %}