app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from app import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += [path('__debug__', include('debug_toolbar.urls'))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods.views import CatalogView, ProductView

app_name = 'goods'

urlpatterns = [
    path('search/', CatalogView.as_view(), name='search'),
    path('<slug:category_slug>/', CatalogView.as_view(), name='index'),
    path('product/<slug:product_slug>/', ProductView.as_view(), name='product'),
]

users/urls.py
from django.urls import path

from users.views import (
    UserCartView,
    UserLoginView,
    UserProfileView,
    UserRegistrationView,
    logout,
)

app_name = 'users'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('users-cart/', UserCartView.as_view(), name='users_cart'),
    path('logout/', logout, name='logout'),
]

orders/models.py
from django.db import models

from goods.models import Product
from users.models import User


class OrderItemQueryset(models.QuerySet):
    def total_price(self) -> int:
        return sum(item.products_price for item in self)

    def total_quantity(self) -> int:
        if self:
            return sum(item.quantity for item in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.SET_DEFAULT,
        verbose_name='Пользователь',
        blank=True,
        null=True,
        default=None,
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона')
    requires_delivery = models.BooleanField(default=False, verbose_name='Доставка')
    delivery_address = models.TextField(blank=True, default='', verbose_name='Адрес доставки')
    payment_upon_delivery = models.BooleanField(default=False, verbose_name='Оплата при получении')
    is_paid = models.BooleanField(default=False, verbose_name='Оплачено')
    status = models.CharField(max_length=50, default='В обработке', verbose_name='Статус заказа')
    user_order_no = models.PositiveIntegerField(verbose_name='Номер заказа покупателя')

    class Meta:
        db_table = 'orders'
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self) -> str:
        if self.user:
            return f'Заказ № {self.pk} Покупатель {self.user.first_name} {self.user.last_name}'
        return f'Заказ № {self.pk} Покупатель неизвестен'


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey(
        to=Product, on_delete=models.SET_DEFAULT, null=True, verbose_name='Товар', default=None
    )
    name = models.CharField(max_length=150, verbose_name='Название')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')

    objects = OrderItemQueryset.as_manager()

    class Meta:
        db_table = 'order_items'
        verbose_name = 'Проданный товар'
        verbose_name_plural = 'Проданные товары'

    def __str__(self) -> str:
        return f'Товар {self.name} Заказ № {self.order.pk}'

    def products_price(self):
        return round(self.price * self.quantity, 2)

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    image = models.ImageField(
        upload_to='users_images',
        blank=True,
        null=True,
        verbose_name='Аватар',
    )
    phone_number = models.CharField(max_length=10, blank=True, default='')
    total_orders = models.PositiveIntegerField(verbose_name='Всего заказов', default=0)

    class Meta:
        db_table = 'users'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('image', 'first_name', 'last_name', 'username', 'email')

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

users/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, TemplateView, UpdateView

from carts.models import Cart
from common.mixins import CacheMixin
from orders.models import Order
from users.forms import UserLoginForm, UserProfileForm, UserRegistrationForm


class UserLoginView(LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm

    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.get_user()
        auth.login(self.request, user)
        Cart.objects.filter(session_key=session_key).update(user=user)
        messages.success(self.request, f'Добро пожаловать, {user.first_name or user.username}.')
        return super().form_valid(form)

    def get_success_url(self):
        if redirect_page := self.request.POST.get('next'):
            return redirect_page
        return reverse_lazy('main:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': 'Home - Авторизация'})
        return context


class UserRegistrationView(CreateView):
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm
    success_url: str = reverse_lazy('user:profile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'title': 'Home - Регистрация'})
        return context

    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.save()
        auth.login(self.request, user)
        Cart.objects.filter(session_key=session_key).update(user=user)
        messages.success(
            self.request,
            f'{user.first_name or user.username}, вы успешно зарегистрировались и вошли в аккаунт.',
        )
        return HttpResponseRedirect(self.success_url)


class UserProfileView(LoginRequiredMixin, CacheMixin, UpdateView):
    template_name = 'users/profile.html'
    form_class = UserProfileForm
    success_url = reverse_lazy('user:profile')

    def get_object(self):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, 'Профиль успешно обновлен')
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home - Профиль'

        orders = (
            Order.objects.filter(user=self.request.user)
            .prefetch_related('orderitem_set__product')
            .order_by('-id')
        )

        context['orders'] = self.set_get_cache(orders, f'user_{self.request.user.pk}_orders', 60)
        return context


class UserCartView(TemplateView):
    template_name = 'users/users_cart.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home - Корзина'
        return context


@login_required
def logout(request):
    messages.success(
        request, f'{request.user.first_name or request.user.username}, вы вышли из аккаунта.'
    )
    auth.logout(request)
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}
{% block modal_cart %}
{% include "includes/cart_button.html" %}
{% endblock modal_cart %}
{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Авторизация</h2>
                    <form action="{% url "user:login" %}" method="post">
                        {% csrf_token %}
                        {% if request.GET.next %}<input type="hidden" name="next" value={{ request.GET.next }}>{% endif %}
                        {% if form.non_field_errors %}<p>{{ form.non_field_errors }}</p>{% endif %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">{{ form.username.label }}</label>
                            <input type="text"
                                   id="id_username"
                                   autofocus="true"
                                   class="form-control"
                                   name="username"
                                   {% if form.username.value %}value="{{ form.username.value }}"{% endif %}
                                   placeholder="Введите имя пользователя">
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">{{ form.password.label }}</label>
                            <input type="password"
                                   id="id_password"
                                   class="form-control"
                                   name="password"
                                   placeholder="Введите пароль">
                        </div>
                        <button type="submit" class="btn btn-dark btn-block">Войти</button>
                    </form>
                    <div class="mt-3">
                        <a href="#">Забыли пароль?</a> | <a href="{% url "user:registration" %}">Создать аккаунт</a>
                    </div>
                    <hr>
                    <div class="text-center">
                        <p>Или авторизуйтесь через:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1"
                                 src="{% static "deps/icons/google.svg" %}"
                                 alt="Catalog Icon"
                                 width="16"
                                 height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1"
                                 src="{% static "deps/icons/facebook.svg" %}"
                                 alt="Catalog Icon"
                                 width="16"
                                 height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1"
                                 src="{% static "deps/icons/github.svg" %}"
                                 alt="Catalog Icon"
                                 width="16"
                                 height="16">
                            GitHub
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}
{% block content %}
    {% user_carts request as carts %}
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="col-md-5">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Профиль пользователя</h3>
                        <form action="{% url "user:profile" %}"
                              method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    {% if user.image %}
                                        <img src="{{ user.image.url }}"
                                             alt="Аватар пользователя"
                                             class="img-fluid rounded-circle"
                                             width="150px">
                                    {% else %}
                                        <img src="{% static "deps/images/baseavatar.jpg" %}"
                                             alt="Аватар пользователя"
                                             class="img-fluid rounded-circle"
                                             width="150px">
                                    {% endif %}
                                    <input type="file"
                                           class="form-control mt-3"
                                           id="id_image"
                                           accept="image/*"
                                           name="image">
                                    {% if form.image.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_first_name" class="form-label">Имя*</label>
                                    <input type="text"
                                           class="form-control"
                                           id="id_first_name"
                                           placeholder="Введите ваше имя"
                                           name="first_name"
                                           value="{{ form.first_name.value }}"
                                           required>
                                    {% if form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_last_name" class="form-label">Фамилия*</label>
                                    <input type="text"
                                           class="form-control"
                                           id="id_last_name"
                                           placeholder="Введите вашу фамилию"
                                           name="last_name"
                                           value="{{ form.last_name.value }}"
                                           required>
                                    {% if form.last_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_username" class="form-label">Имя пользователя*</label>
                                    <input type="text"
                                           class="form-control"
                                           id="id_username"
                                           placeholder="Введите ваше имя пользователя"
                                           name="username"
                                           value="{{ form.username.value }}"
                                           required>
                                    {% if form.username.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_email" class="form-label">Email*</label>
                                    <input type="email"
                                           class="form-control"
                                           id="id_email"
                                           placeholder="Введите ваш email *youremail@example.com"
                                           name="email"
                                           value="{{ form.email.value }}"
                                           required>
                                    {% if form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">Сохранить</button>
                        </form>
                    </div>
                </div>
                <!-- Корзина -->
                <div class="col-md-7">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Корзина</h3>
                        <div class="container" id="cart-items-container">
                            <!-- Разметка корзины -->
                            {% include "carts/includes/included_cart.html" %}
                            <!-- Закончилась разметка корзины -->
                        </div>
                    </div>
                </div>
                <!-- Оформленные заказы -->
                <div class="col-md-12">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Мои заказы</h3>
                        <!-- Разметка заказов -->
                        <div class="container">
                            <div class="accordion" id="heading{{ order.id }}">
                                {% for order in orders %}
                                    <div class="accordion-item">
                                        <h2 class="accordion-header" id="heading{{ order.id }}">
                                            <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}"
                                                    type="button"
                                                    data-bs-toggle="collapse"
                                                    data-bs-target="#collapse{{ order.id }}"
                                                    aria-expanded="false"
                                                    aria-controls="collapse{{ order.id }}">
                                                Заказ № {{ order.user_order_no }} - {{ order.created_timestamp }} | Статус: <strong class="mx-2">{{ order.status }}</strong>
                                            </button>
                                        </h2>
                                        <div id="collapse{{ order.id }}"
                                             class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}"
                                             aria-labelledby="heading{{ order.id }}"
                                             data-bs-parent="#accordionExample">
                                            <div class="accordion-body">
                                                <table class="table table-dark table-hover">
                                                    <thead>
                                                        <tr>
                                                            <th>Товар</th>
                                                            <th>Количество</th>
                                                            <th>Цена</th>
                                                            <th>Общая стоимость</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        {% for item in order.orderitem_set.all %}
                                                            <tr>
                                                                <td>
                                                                    <a class="text-white" href="{% url 'goods:product' item.product.slug %}">{{ item.product.name }}</a>
                                                                </td>
                                                                <td>{{ item.quantity }}</td>
                                                                <td>{{ item.price }}</td>
                                                                <td>{{ item.products_price }}</td>
                                                            </tr>
                                                        {% endfor %}
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <!-- Закончилась разметка заказов -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/registration.html
{% extends "base.html" %}
{% load static %}
{% block modal_cart %}
    {% include "includes/cart_button.html" %}
{% endblock modal_cart %}
{% block content %}
    <div class="container">
        <div class="row mt-1">
            <div class="col-lg-2">
                <!-- Пустой блок на усмотрение -->
            </div>
            <div class="col-lg-10">
                <!-- Контент на странице -->
                <div class="row">
                    <div class="container mt-5">
                        <div class="row justify-content-center">
                            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                                <h2 class="text-center mb-4">Регистрация</h2>
                                <form action="{% url "user:registration" %}" method="post">
                                    {% csrf_token %}
                                    <div class="row">
                                        <div class="col-md-6 mb-3">
                                            <label for="id_first_name" class="form-label">Имя*</label>
                                            <input type="text"
                                                   class="form-control"
                                                   id="id_first_name"
                                                   name="first_name"
                                                   {% if form.first_name.value %}value="{{ form.first_name.value }}"{% endif %}
                                                   placeholder="Введите ваше имя"
                                                   required>
                                            {% if form.first_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_last_name" class="form-label">Фамилия*</label>
                                            <input type="text"
                                                   class="form-control"
                                                   id="id_last_name"
                                                   name="last_name"
                                                   {% if form.last_name.value %}value="{{ form.last_name.value }}"{% endif %}
                                                   placeholder="Введите вашу фамилию"
                                                   required>
                                            {% if form.last_name.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_username" class="form-label">Имя пользователя*</label>
                                            <input type="text"
                                                   class="form-control"
                                                   id="id_username"
                                                   name="username"
                                                   {% if form.username.value %}value="{{ form.username.value }}"{% endif %}
                                                   placeholder="Введите ваше имя пользователя"
                                                   required>
                                            {% if form.username.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_email" class="form-label">Email*</label>
                                            <input type="email"
                                                   class="form-control"
                                                   id="id_email"
                                                   name="email"
                                                   {% if form.email.value %}value="{{ form.email.value }}"{% endif %}
                                                   placeholder="Введите ваш email"
                                                   required>
                                            {% if form.email.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_password1" class="form-label">Пароль*</label>
                                            <input type="password"
                                                   class="form-control"
                                                   id="id_password1"
                                                   name="password1"
                                                   {% if form.password1.value %}value="{{ form.password1.value }}"{% endif %}
                                                   placeholder="Введите пароль"
                                                   required>
                                            {% if form.password1.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                            {% endif %}
                                        </div>
                                        <div class="col-md-6 mb-3">
                                            <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                            <input type="password"
                                                   class="form-control"
                                                   id="id_password2"
                                                   name="password2"
                                                   {% if form.password2.value %}value="{{ form.password2.value }}"{% endif %}
                                                   placeholder="Подтвердите пароль"
                                                   required>
                                            {% if form.password2.errors %}
                                                <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                            {% endif %}
                                        </div>
                                    </div>
                                    <button type="submit" class="btn btn-dark btn-block">Зарегистрироваться</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}